name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

defaults:
  run:
    shell: bash

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Set cache variables
        id: variables
        run: |
          echo "cache-dir=$(yarn cache dir)" >>"${GITHUB_OUTPUT}"

      - name: Setup cache - read only
        uses: actions/cache/restore@v4
        if: ${{ github.ref != format('refs/heads/{0}', github.event.repository.default_branch ) }}
        env:
          cache_name_prefix: node-cache
        with:
          path: ${{ steps.variables.outputs.cache-dir }}
          key: ${{ env.cache_name_prefix }}-${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ env.cache_name_prefix }}-${{ runner.os }}-yarn-

      - name: Setup cache
        uses: actions/cache@v4
        if: ${{ github.ref == format('refs/heads/{0}', github.event.repository.default_branch ) }}
        env:
          cache_name_prefix: node-cache
        with:
          path: ${{ steps.variables.outputs.cache-dir }}
          key: ${{ env.cache_name_prefix }}-${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ env.cache_name_prefix }}-${{ runner.os }}-yarn-

      - run: yarn install --immutable --immutable-cache --check-cache

      - run: yarn tsc

      - run: yarn prettier:check

      - run: yarn lint:all

      - run: yarn test:all

      - run: yarn build:all

      - name: Upload app artifact
        uses: actions/upload-artifact@v4
        with:
          name: app
          path: packages/app/dist
          retention-days: 5
          if-no-files-found: error

      - name: Upload backend artifact
        uses: actions/upload-artifact@v4
        with:
          name: backend
          path: packages/backend/dist
          retention-days: 5
          if-no-files-found: error

  package-app:
    name: Package app
    needs: build
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/package.yaml
    with:
      type: app

  package-backend:
    name: Package backend
    needs: build
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/package.yaml
    with:
      type: backend

  dependabot-merge:
    name: Dependabot Merge
    if: |
      github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest
    needs:
      - package-app
      - package-backend
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Dependabot Merge
        uses: fastify/github-action-merge-dependabot@v3
        with:
          target: minor
