name: Lint and Test

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'yarn'
      - run: yarn install --frozen-lockfile
      - run: yarn tsc
      - run: yarn prettier:check
      - run: yarn lint:all
      - run: yarn test:all
